/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	context "context"

	v1 "github.com/kubeovn/kube-ovn/pkg/apis/kubeovn/v1"
	kubeovnv1 "github.com/kubeovn/kube-ovn/pkg/client/clientset/versioned/typed/kubeovn/v1"
	autoscalingv1 "k8s.io/api/autoscaling/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	gentype "k8s.io/client-go/gentype"
	testing "k8s.io/client-go/testing"
)

// fakeVpcEdgeRouters implements VpcEdgeRouterInterface
type fakeVpcEdgeRouters struct {
	*gentype.FakeClientWithList[*v1.VpcEdgeRouter, *v1.VpcEdgeRouterList]
	Fake *FakeKubeovnV1
}

func newFakeVpcEdgeRouters(fake *FakeKubeovnV1, namespace string) kubeovnv1.VpcEdgeRouterInterface {
	return &fakeVpcEdgeRouters{
		gentype.NewFakeClientWithList[*v1.VpcEdgeRouter, *v1.VpcEdgeRouterList](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("vpc-edge-routers"),
			v1.SchemeGroupVersion.WithKind("VpcEdgeRouter"),
			func() *v1.VpcEdgeRouter { return &v1.VpcEdgeRouter{} },
			func() *v1.VpcEdgeRouterList { return &v1.VpcEdgeRouterList{} },
			func(dst, src *v1.VpcEdgeRouterList) { dst.ListMeta = src.ListMeta },
			func(list *v1.VpcEdgeRouterList) []*v1.VpcEdgeRouter { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.VpcEdgeRouterList, items []*v1.VpcEdgeRouter) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}

// GetScale takes name of the vpcEdgeRouter, and returns the corresponding scale object, and an error if there is any.
func (c *fakeVpcEdgeRouters) GetScale(ctx context.Context, vpcEdgeRouterName string, options metav1.GetOptions) (result *autoscalingv1.Scale, err error) {
	emptyResult := &autoscalingv1.Scale{}
	obj, err := c.Fake.
		Invokes(testing.NewGetSubresourceActionWithOptions(c.Resource(), c.Namespace(), "scale", vpcEdgeRouterName, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*autoscalingv1.Scale), err
}

// UpdateScale takes the representation of a scale and updates it. Returns the server's representation of the scale, and an error, if there is any.
func (c *fakeVpcEdgeRouters) UpdateScale(ctx context.Context, vpcEdgeRouterName string, scale *autoscalingv1.Scale, opts metav1.UpdateOptions) (result *autoscalingv1.Scale, err error) {
	emptyResult := &autoscalingv1.Scale{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceActionWithOptions(c.Resource(), "scale", c.Namespace(), scale, opts), &autoscalingv1.Scale{})

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*autoscalingv1.Scale), err
}
