/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	kubeovnv1 "github.com/kubeovn/kube-ovn/pkg/apis/kubeovn/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// VpcEdgeRouterLister helps list VpcEdgeRouters.
// All objects returned here must be treated as read-only.
type VpcEdgeRouterLister interface {
	// List lists all VpcEdgeRouters in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kubeovnv1.VpcEdgeRouter, err error)
	// VpcEdgeRouters returns an object that can list and get VpcEdgeRouters.
	VpcEdgeRouters(namespace string) VpcEdgeRouterNamespaceLister
	VpcEdgeRouterListerExpansion
}

// vpcEdgeRouterLister implements the VpcEdgeRouterLister interface.
type vpcEdgeRouterLister struct {
	listers.ResourceIndexer[*kubeovnv1.VpcEdgeRouter]
}

// NewVpcEdgeRouterLister returns a new VpcEdgeRouterLister.
func NewVpcEdgeRouterLister(indexer cache.Indexer) VpcEdgeRouterLister {
	return &vpcEdgeRouterLister{listers.New[*kubeovnv1.VpcEdgeRouter](indexer, kubeovnv1.Resource("vpcedgerouter"))}
}

// VpcEdgeRouters returns an object that can list and get VpcEdgeRouters.
func (s *vpcEdgeRouterLister) VpcEdgeRouters(namespace string) VpcEdgeRouterNamespaceLister {
	return vpcEdgeRouterNamespaceLister{listers.NewNamespaced[*kubeovnv1.VpcEdgeRouter](s.ResourceIndexer, namespace)}
}

// VpcEdgeRouterNamespaceLister helps list and get VpcEdgeRouters.
// All objects returned here must be treated as read-only.
type VpcEdgeRouterNamespaceLister interface {
	// List lists all VpcEdgeRouters in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kubeovnv1.VpcEdgeRouter, err error)
	// Get retrieves the VpcEdgeRouter from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*kubeovnv1.VpcEdgeRouter, error)
	VpcEdgeRouterNamespaceListerExpansion
}

// vpcEdgeRouterNamespaceLister implements the VpcEdgeRouterNamespaceLister
// interface.
type vpcEdgeRouterNamespaceLister struct {
	listers.ResourceIndexer[*kubeovnv1.VpcEdgeRouter]
}
